### ISSUE TITLE
add

### ISSUE THREAD

**Issue by FightnightKidd** [justinnobledev/cs2-spawntools#2]
@spawntools/add admin where is this and is it by name or steam id?

**Comment by hamilton5** [comment]
that is the flag your 'admin' needs to use the command. see: https://docs.cssharp.dev/docs/admin-framework/defining-admins.html

**Comment by Ryuujin555** [comment]
also having same problem with adding rights ._. i'm using plugin for admins connected to msq base with all possible rights and this plugin still won't allow me to use command with adding spawn - do it read admins from somewhere else or certain file ? could someone paste an example how it should like ?

**Comment by hamilton5** [comment]
start by showing output of your `css_admins_list` command
